FROM yidadaa/chatgpt-next-web
ENV HIDE_USER_API_KEY=1
ENV BASE_URL=https://dongsiqie-bingai.hf.space
ENV OPENAI_API_KEY=sk-bing
ENV CUSTOM_MODELS=-all,+Creative-g4t,+Balanced-g4t,+Precise-g4t,+Creative,+Balanced,+Precise,+Creative-g4t-offline,+Balanced-g4t-offline,+Precise-g4t-offline,+Creative-offline,+Balanced-offline,+Precise-offline